FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /src

COPY PersonalTrainer.Api.csproj ./
RUN dotnet restore PersonalTrainer.Api.csproj

COPY . ./

ENV ASPNETCORE_URLS=http://0.0.0.0:5050
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 5050

ENTRYPOINT ["dotnet", "watch", "run", "--project", "PersonalTrainer.Api.csproj", "--urls", "http://0.0.0.0:5050", "--non-interactive"]
